config/routes.rb
App::Application.routes.draw do
  root 'pages#index'
  resources :pages, only: [:index, :create], path: ""
  get '/add' => 'pages#new', as: :new_page
  get '/*names/add' => 'pages#new', as: :new_subpage
  get '/*names/edit' => 'pages#edit', as: :edit_page
  get '/*names' => 'pages#show', as: :page
  patch '/*names' => 'pages#update', as: :update_page
  post '/*names' => 'pages#create', as: :create_subpage
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :parent, class_name: 'Page'
  has_many :childrens, class_name: 'Page', foreign_key: 'parent_id'
  validates :name, presence: true, format: { with: /\A[a-zA-Z0-9_а-яА-Я]+\z/ }
  validates :header, presence: true
  before_save :edit_page
  before_update :edit_page
  
  # Функция для преобразования параметров страницы
  def edit_page
    # Русское название переводим в транслит
    self.name = normalize_friendly_id(self.name)
    # Преобразование в жирный шрифт
    self.description.scan(/\*.+\*/).each do |b|
      self.description.gsub!(b, "<b>" + b[1..-2] + "</b>")
    end
    # Преобразование в курсив
    self.description.scan(/\\.+\\/).each do |i|
      self.description.gsub!(i, "<i>" + i[1..-2] + "</i>")
    end
    self.description.gsub!("\\", "")
    # Преобразование в ссылку
    self.description.scan(/\(\([a-zA-Z0-9_а-яА-Я\/]+ .+\)\)/).each do |a|
      path, str = a[2..-3].split(" ")
      self.description.gsub!(a, "<a href='http://0.0.0.0:3000/#{path}'>#{str}</a>")
    end
  end

  # Обратное преобразование текста для редактирования пользователем
  def unreplace_description
    return "" unless self.description
    # Преобразование из жирного шрифта и курсива
    description = self.description.gsub(/<b>|<\/b>/, "*").gsub(/<i>|<\/i>/, "\\")
    # Преобразование из ссылки
    description.scan(/<a href='.+'>.+<\/a>/).each do |a|
      link = a.match(/<a href='http:\/\/0.0.0.0:3000\/(.+)'>(.+)<\/a>/)
      description.gsub!(a, "((" + link[1..2].join(" ") + "))" ) if link
    end
    description
  end

  def normalize_friendly_id(text)
    text.to_slug.transliterate(:russian).normalize.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_names, only: [:new, :edit, :show, :update, :create]
  before_action :validate_route, only: [:new, :edit, :show]
  before_action :set_page, only: [:update]

  # GET /
  def index
    @pages = Page.all
  end

  # GET /*names
  def show
    @pages = Page.all
  end

  # GET /add
  # GET /*names/add
  def new
    @page = Page.new
    if params[:names].present?
      @page.parent_id = Page.friendly.find(@names.last).id
    end
  end

  # GET /*names/edit
  def edit
  end

  # POST /
  # POST /*names
  def create
    if params[:names].present?
      @page = Page.new(page_params.merge({parent_id: Page.friendly.find(@names.last).id}))
    else
      @page = Page.new(page_params)
    end
  
    respond_to do |format|
      url = params[:names] ? params[:names] + "/" : ""
      if @page.save
        format.html { redirect_to page_path(url + @page.name), notice: 'Page was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH /*names
  def update
    respond_to do |format|
      if @page.update(page_params)
        @names[-1] = page_params[:name]
        format.html { redirect_to page_path(@names.join("/")), notice: 'Page was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  private
    def set_page
      @page = Page.friendly.find(@names.last)
    end

    def page_params
      params[:page].permit(:parent_id, :name, :header, :description)
    end

    def set_names
      @names = params[:names] ? params[:names].split("/") : nil
    end

    def validate_route
      return unless params[:names] 
      # Проверка правильности пути достраницы
      pages = Page.friendly.where(name: @names)
      @page = pages.detect{ |page| page.name == @names.last }
      # Если не существует какой-то страницы отдать 404
      not_found if @names.size != pages.count

      pages = pages.map { |page| { page.id => page.attributes.symbolize_keys.slice(:parent_id, :name) } }
      pages = pages.reduce(Hash.new, :merge)
      
      valid_str = [@page.name]
      cur_page = @page
      while valid_str.size < pages.size do
        cur_page = pages[cur_page[:parent_id]]
        # Не нашли нужную запись страницы значит неверный путь
        not_found if cur_page.nil?

        valid_str << cur_page[:name]
      end

      # Итоговая проверка верности пути
      not_found if valid_str.reverse.join("/") != params[:names] || cur_page[:parent_id] != nil
    end

    def not_found
      raise ActionController::RoutingError.new('Not Found')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_child.html.erb
<% child[:pages].select{|page| page.parent_id == child[:parent_id] }.each do |children| %>
  <% child_url = child[:cost_name] + "/" + children.name %>
  <div style="margin-left: <%= child[:level] * 10 %>px">
    <%= link_to children.name, page_path(child_url) %>
  </div>
  <%= render partial: "child", object: { parent_id: children.id, cost_name: child_url, pages: child[:pages], level: child[:level] + 1 } %>
<% end %>

app/views/pages/_form.html.erb
<%= form_for(@page, url: @page.new_record? ? (params[:names] ? create_subpage_path(params[:names]) : pages_path) : update_page_path(params[:names]) ) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.hidden_field 'parent_id', value: @page.parent_id %>
    <div>
      <%= label_tag 'Name' %>
      <%= f.text_field :name, value: @page.name, required: true %>
    </div>
    <div>
      <%= label_tag 'Header' %>
      <%= f.text_field :header, value: @page.header, required: true %>
    </div>
    <div>
      <%= label_tag 'Description' %>
      <%= f.text_area :description, value: @page.unreplace_description, size: "colsxrols" %>
    </div>
  <div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

app/views/pages/index.html.erb
<h1>Main page</h1>

<% @pages.select{ |page| page.parent_id.nil? }.each do |page|%>
  <div>
    <%= link_to page.name, page_path(page.name) %>
  </div>
  <%= render partial: "child", object: { parent_id: page.id, cost_name: page.name, pages: @pages, level: 1 } %>
<% end %>

<br>
<% if @pages.blank? %>
  <%= link_to 'Create Main Page', new_page_path %>
<% end %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(page_path(CGI.unescape(params[:names]))) do |f| %>
  <div>
    <%= f.hidden_field 'parent_id', value: @page.parent_id %>
    <div>
      Name: <%= label_tag 'name', @page.name %>
    </div>
    <div>
      Header: <%= label_tag 'header', @page.header %>
    </div>
    <div>
      Description: 
      <div>
        <%= @page.description.html_safe %>
      </div>
    </div>
  <div>
<% end %>

<%= link_to 'Edit', edit_page_path(CGI.unescape(params[:names])) %> | <%= link_to 'Create SubPage', new_subpage_path(CGI.unescape(params[:names])) %>

<% @pages.select{ |page| page.id == @page.id }.each do |page|%>
  <%= render partial: "child", object: { parent_id: page.id, cost_name: page.name, pages: @pages, level: 1 } %>
<% end %>